[project]
name = 'Tokenized-Biodiversity-Conservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.conservation-initiative]
path = 'contracts/conservation-initiative.clar'
clarity_version = 2
epoch = 2.5

[contracts.habitat-verification]
path = 'contracts/habitat-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.species-tracking]
path = 'contracts/species-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
